### ISSUE TITLE
Beispiele

### ISSUE THREAD

**Issue by adieball** [ubittner/SymconPushover#3]
Hi

hast Du mal ein paar "echte" Bespiele?
Wenn ich die Beispiele aus der Readme nehme und die Variablen ersetze, bekomme ich nur ein:

Parse error: syntax error, unexpected 'is' (T_STRING), expecting ',' or ')' in /var/lib/symcon/scripts/50393.ips.php on line 3

**Comment by ubittner** [comment]
$instanceID = 12345; // Instanz ID deiner Pushover Instanz, muss angepasst werden
$push = UBPO_SendPushoverNotification($instanceID, 'Test', 'Dies ist ein Test');

**Comment by adieball** [comment]
damned.... das $push hatte ich vergessen, danke für den Schlag auf den Hinterkopf :-)
